routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('','LoginController@view_login')->name('view_login');
Route::post('process_login','LoginController@process_login')->name('process_login');

Route::group(['middleware' => 'CheckLogin'], function(){
	Route::get('welcome','LoginController@welcome')->name('welcome');
	Route::get('logout','LoginController@logout')->name('logout');
	Route::get('change_password','LoginController@change_password')->name('change_password');
	Route::post('update_admin_password','LoginController@update_admin_password')->name('update_admin_password');

	Route::resource('khach_hang','KhachHangController');
	Route::resource('hoa_don','HoaDonController');
	Route::resource('dich_vu','DichVuController');
	Route::resource('dat_dich_vu','DatDichVuController');
	Route::resource('dat_phong','DatPhongController');
	Route::resource('vat_tu','VatTuController');
	Route::resource('kho','KhoController');
	Route::resource('loai_phong','LoaiPhongController');
	Route::resource('loai_phong/{ma_loai_phong}/vat_tu','VatTuLoaiPhongController')->names('vat_tu_loai_phong');
	Route::resource('phong','PhongController');
	Route::resource('phong/{ma_phong}/vat_tu','VatTuPhongController')->names('vat_tu_phong');

	Route::get('thong_ke','ThongKeController@index')->name('thong_ke');
});

Route::group(['as' => 'ajax.', 'prefix' => 'ajax'], function() {
	Route::get('get_dich_vu','AjaxController@getDichVu')->name('get_dich_vu');
	Route::get('get_phong','AjaxController@getPhong')->name('get_phong');
	Route::get('get_hoa_don_phong','AjaxController@getHoaDonPhong')->name('get_hoa_don_phong');
	Route::get('get_thong_ke','AjaxController@getThongKe')->name('get_thong_ke');
	Route::get('get_thong_ke_noi_bat','AjaxController@getThongKeNoiBat')->name('get_thong_ke_noi_bat');
});

Route::resource('test_searching', 'TestController');

app/Http/Controllers/DichVuController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\DichVuRequest;
use App\Http\Requests\EditDichVuRequest;
use App\Models\DichVuModel;
use App\Models\TrangThaiDichVuModel;

class DichVuController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $ten_dich_vu        = $request->ten_dich_vu;
        $trang_thai_dich_vu = $request->trang_thai_dich_vu;

        $array_trang_thai_dich_vu = TrangThaiDichVuModel::all();

        $array_dich_vu = DichVuModel::join('trang_thai_dich_vu','dich_vu.ma_trang_thai_dich_vu','trang_thai_dich_vu.ma_trang_thai_dich_vu')
            ->when($trang_thai_dich_vu, function($query) use ($trang_thai_dich_vu){
                return $query->whereIn('dich_vu.ma_trang_thai_dich_vu', $trang_thai_dich_vu);
            })
            ->when($ten_dich_vu, function($query) use ($ten_dich_vu){
                return $query->where('dich_vu.ten_dich_vu','like','%'.$ten_dich_vu.'%');
            })
            ->orderBy('ma_dich_vu')
            ->paginate(5);

        return view('dich_vu.view_all_dv',[
            'array_dich_vu'            => $array_dich_vu,
            'trang_thai_dich_vu'       => $trang_thai_dich_vu,
            'ten_dich_vu'              => $ten_dich_vu,
            'array_trang_thai_dich_vu' => $array_trang_thai_dich_vu,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(DichVuRequest $request)
    {
        $dich_vu                     = new DichVuModel();
        $dich_vu->ten_dich_vu        = $request->ten_dich_vu;
        $dich_vu->gia_dich_vu        = $request->gia_dich_vu;
        $dich_vu->don_vi_dich_vu     = $request->don_vi_dich_vu;
        $dich_vu->ma_trang_thai_dich_vu = $request->trang_thai_dich_vu;
        $dich_vu->save();

        return redirect()->route('dich_vu.index')->with('success','Thêm dịch vụ thành công!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($ma_dich_vu)
    {
        $dich_vu = DichVuModel::find($ma_dich_vu);

        // return view('dich_vu.edit_dv',[
        //     'dich_vu' => $dich_vu
        // ]);
        return json_encode(array('dich_vu' => $dich_vu));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(EditDichVuRequest $request, $ma_dich_vu)
    {
        DichVuModel::find($ma_dich_vu)->update($request->all());
        
        return redirect()->route('dich_vu.index')->with('success','Thay đổi trạng thái dịch vụ thành công!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($ma_dich_vu)
    {
        DichVuModel::find($ma_dich_vu)->delete();

        return redirect()->route('dich_vu.index')->with('success','Đã xóa dịch vụ!');
    }
}

resources/views/dich_vu/create_dv.blade.php
@extends('layout.master')

@section('title', 'Thêm dịch vụ')

@section('navigation')
<a href="{{ route('dich_vu.index') }}">Dịch vụ</a> → Thêm dịch vụ
@endsection

@section('search')
@endsection

@section('content')
<div class="grid_1">
	<div>
		Điền thông tin của dịch vụ:
		<form action="{{ route('dich_vu.store') }}" method="POST">
			{{ csrf_field() }}
			Tên dịch vụ
			<br>
			<input type="text" name="ten_dich_vu" value="{{ old('ten_dich_vu') }}">
			@if ($errors->has('ten_dich_vu'))
				<span class="validate_msg">{{ $errors->first('ten_dich_vu') }}</span>
			@endif
			<br>
			Giá dịch vụ
			<br>
			<input type="text" name="gia_dich_vu" value="{{ old('gia_dich_vu') }}">
			@if ($errors->has('gia_dich_vu'))
				<span class="validate_msg">{{ $errors->first('gia_dich_vu') }}</span>
			@endif
			<br>
			Đơn vị
			<br>
			<input type="text" name="don_vi_dich_vu" value="{{ old('don_vi_dich_vu') }}">
			@if ($errors->has('don_vi_dich_vu'))
				<span class="validate_msg">{{ $errors->first('don_vi_dich_vu') }}</span>
			@endif
			<br>
			Trạng thái
			<br>
			<select name="trang_thai_dich_vu">
				<option value="1">Sẵn sàng</option>
				<option value="0">Hết dịch vụ</option>
				<option value="2">Tạm ngưng</option>
			</select>
			@if ($errors->has('trang_thai_dich_vu'))
				<span class="validate_msg">{{ $errors->first('trang_thai_dich_vu') }}</span>
			@endif
			<br>
			<button class="form_button_success">Thêm</button>
		</form>
	</div>
</div>
@endsection

resources/views/dich_vu/edit_dv.blade.php
@extends('layout.master')

@section('title', 'Chỉnh sửa dịch vụ')

@section('navigation')
<a href="{{ route('dich_vu.index') }}">Dịch vụ</a> → Chỉnh sửa dịch vụ
@endsection

@section('search')
@endsection

@section('content')
<div class="grid_1">
	<div>
		Chỉnh sửa dịch vụ:
		<form action="{{ route('dich_vu.update', ['ma_dich_vu' => $dich_vu->ma_dich_vu]) }}" method="POST">
			{{ method_field('PUT') }}
			{{ csrf_field() }}
			Tên dịch vụ
			<br>
			<input type="text" name="ten_dich_vu" value="{{ $dich_vu->ten_dich_vu }}">
			@if ($errors->has('ten_dich_vu'))
				<span class="validate_msg">{{ $errors->first('ten_dich_vu') }}</span>
			@endif
			<br>
			Giá dịch vụ (VND)
			<br>
			<input type="text" name="gia_dich_vu" value="{{ $dich_vu->gia_dich_vu }}">
			@if ($errors->has('gia_dich_vu'))
				<span class="validate_msg">{{ $errors->first('gia_dich_vu') }}</span>
			@endif
			<br>
			Đơn vị tính
			<br>
			<input type="text" name="don_vi_dich_vu" value="{{ $dich_vu->don_vi_dich_vu }}">
			@if ($errors->has('don_vi_dich_vu'))
				<span class="validate_msg">{{ $errors->first('don_vi_dich_vu') }}</span>
			@endif
			<br>
			<button id="button_submit" class="form_button_success">Thay đổi</button>
		</form>
	</div>
</div>
@endsection

resources/views/dich_vu/order_dv.blade.php
@extends('layout.master')

@section('title', 'Đặt dịch vụ')

@section('navigation')
<a href="{{ route('dich_vu.index') }}">Dịch vụ</a> → Đặt dịch vụ
@endsection

@section('search')
@endsection

@section('content')
<div class="grid_1">
	<div class="grid_content">
		<form action="{{ route('dat_dich_vu.store') }}" method="POST">
			{{ csrf_field() }}
			Chọn hóa đơn
			<br>
			<select name="ma_hoa_don" id="ma_hoa_don">
				<option></option>
				@foreach ($array_hoa_don as $each)
					<option value="{{ $each->ma_hoa_don }}">{{ $each->ten_kh }} - #{{ $each->ma_hoa_don }}</option>
				@endforeach
			</select>
			@if ($errors->has('ma_hoa_don'))
				<span class="validate_msg">{{ $errors->first('ma_hoa_don') }}</span>
			@endif
			<br>
			Chọn dịch vụ
			<br>
			<select name="ma_dich_vu[]" id="ma_dich_vu_select" class="select_item" style="width: 180px" data-placeholder="Dịch vụ" multiple="multiple">
				@foreach ($array_dich_vu as $each)
					<option value="{{ $each->ma_dich_vu }}">{{ $each->ten_dich_vu }} ({{ $each->don_vi_dich_vu }})</option>
				@endforeach
			</select>
			@if ($errors->has('ma_dich_vu'))
				<span class="validate_msg">{{ $errors->first('ma_dich_vu') }}</span>
			@endif
			<div id="target_don_vi" class="disable_grid">Hãy chọn dịch vụ để điền số lượng</div>
			{{-- <br>
			Số lượng
			<br>
			<input type="text" name="so_luong_dich_vu"> <span id="target_don_vi">đơn vị</span>
			<br> --}}
			@if ($errors->has('so_luong_dich_vu.*'))
				<span class="validate_msg">{{ $errors->first('so_luong_dich_vu.*') }}</span>
			@endif
			<button class="form_button_success">Đặt</button>
			<br>
			*Lưu ý: Thời gian lấy tại thời điểm đặt
		</form>
	</div>
</div>
@endsection

@push('script')
<script type="text/javascript">
$(document).ready(function() {
	$('.select_item').select2({
		width: 'resolve'
	});
	$('#ma_hoa_don').select2({
		placeholder: 'Chọn hóa đơn'
	});
	$("#ma_dich_vu_select").change(function () {
		var ma_dich_vu = $(this).val();
		$("#target_don_vi").html('');
		$.ajax({
			url: '{{ route('ajax.get_dich_vu') }}',
			type: 'GET',
			dataType: 'json',
			data: {ma_dich_vu: ma_dich_vu},
		})
		.done(function(response) {
			$(response).each(function() {
				$("#target_don_vi").append(`
					<table>
						<tr>
							<td>Dịch vụ</td>
							<td><input type="text" value="${this.ten_dich_vu}" disabled></td>
						</tr>
						<tr>
							<td>Số lượng</td>
							<td><input type="number" name="so_luong_dich_vu[${this.ma_dich_vu}]">${this.don_vi_dich_vu}</td>
						</tr>
					</table>
				`);
			});
		})
		.fail(function() {
			console.log("error");
		})
	});
});
</script>
@endpush

resources/views/dich_vu/view_all_dv.blade.php
@extends('layout.master')

@section('title', 'Dịch vụ')

@section('navigation')
Dịch vụ
@endsection

@section('search')
<form action="{{ route('dich_vu.index') }}" method="GET">
	<select class="search_item" name="trang_thai_dich_vu[]" multiple="multiple" data-placeholder="Chọn tình trạng" style="width: 150px">
		@foreach ($array_trang_thai_dich_vu as $each)
			@if (isset($trang_thai_dich_vu) && in_array($each->ma_trang_thai_dich_vu, $trang_thai_dich_vu))
				<option value="{{ $each->ma_trang_thai_dich_vu }}" selected>{{ $each->ten_trang_thai_dich_vu }}</option>
			@else
				<option value="{{ $each->ma_trang_thai_dich_vu }}">{{ $each->ten_trang_thai_dich_vu }}</option>
			@endif
		@endforeach
	</select>
	<input type="text" name="ten_dich_vu" placeholder="Tên dịch vụ" value="{{ $ten_dich_vu }}" style="width: 120px;">
	<button class="form_button_success">Tìm kiếm</button>
</form>
@endsection

@section('form_popup')
<div class="form_popup" id="create_dich_vu">
	<div class="form_popup_header">
		<span class="form_popup_close_button">&times;</span>
		<span class="form_popup_title">Thêm dịch vụ mới</span>
	</div>
	<div class="form_popup_content">
		<form action="{{ route('dich_vu.store') }}" method="POST">
		{{ csrf_field() }}
		<table class="form_popup_table">
			<tr>
				<td class="form_popup_td_label">Tên dịch vụ</td>
				<td class="form_popup_td_input">
					<input type="text" name="ten_dich_vu" placeholder="VD: Bò Húc" value="{{ old('ten_dich_vu') }}">
				</td>
			</tr>
			<tr>
				<td class="form_popup_td_label">Giá dịch vụ (VND)</td>
				<td class="form_popup_td_input">
					<input type="number" name="gia_dich_vu" placeholder="VD: 10000" value="{{ old('gia_dich_vu') }}">
				</td>
			</tr>
			<tr>
				<td class="form_popup_td_label">Đơn vị tính</td>
				<td class="form_popup_td_input">
					<input type="text" name="don_vi_dich_vu" placeholder="VD: Lon" value="{{ old('don_vi_dich_vu') }}">
				</td>
			</tr>
			<tr>
				<td class="form_popup_td_label">Trạng thái</td>
				<td class="form_popup_td_input">
					<select name="trang_thai_dich_vu" id="trang_thai_dich_vu">
						<option></option>
						@foreach ($array_trang_thai_dich_vu as $each)
							<option value="{{ $each->ma_trang_thai_dich_vu }}">{{ $each->ten_trang_thai_dich_vu }}</option>
						@endforeach
					</select>
				</td>
			</tr>
			<tr>
				<td colspan="2">
					<button class="form_button_success">Thêm</button>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>
<div class="form_popup" id="edit_dich_vu">
	<div class="form_popup_header">
		<span class="form_popup_close_button">&times;</span>
		<span class="form_popup_title">Sửa đổi dịch vụ</span>
	</div>
	<div class="form_popup_content">
		<form method="POST">
			{{ method_field('PUT') }}
			{{ csrf_field() }}
		<table class="form_popup_table">
			<tr>
				<td class="form_popup_td_label">Tên dịch vụ</td>
				<td class="form_popup_td_input">
					<input type="text" name="ten_dich_vu" placeholder="VD: Bò Húc" id="ten_dich_vu_edit">
				</td>
			</tr>
			<tr>
				<td class="form_popup_td_label">Giá dịch vụ (VND)</td>
				<td class="form_popup_td_input">
					<input type="number" name="gia_dich_vu" placeholder="VD: 10000" id="gia_dich_vu_edit">
				</td>
			</tr>
			<tr>
				<td class="form_popup_td_label">Đơn vị tính</td>
				<td class="form_popup_td_input">
					<input type="text" name="don_vi_dich_vu" placeholder="VD: Lon" id="don_vi_dich_vu_edit">
				</td>
			</tr>
			<tr>
				<td colspan="2">
					<button class="form_button_success">Sửa</button>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>
@endsection

@section('content')
<div class="grid_1">
	<div class="grid_content">
		<a class="form_button_success open_popup_form" id="button_create_dich_vu">Thêm dịch vụ</a>
		<table class="form_table">
			<tr>
				<th>Tên dịch vụ</th>
				<th>Giá dịch vụ (VND)</th>
				<th>Đơn vị tính</th>
				<th>Trạng thái</th>
				<th colspan="3">Thao tác</th>
			</tr>
			@if ($array_dich_vu->isEmpty())
				<tr>
					<td colspan="5">Không có dữ liệu</td>
				</tr>
			@else
			@foreach ($array_dich_vu as $each)
				<tr>
					<td>
						<p>
							{{ $each->ten_dich_vu }}
						</p>
					</td>
					<td>
						<p>
							{{ number_format($each->gia_dich_vu) }}
						</p>
					</td>
					<td>
						<p>
							{{ $each->don_vi_dich_vu }}
						</p>
					</td>
					<td>
						<p>
							{{ $each->ten_trang_thai_dich_vu }}
						</p>
					</td>
					<td>
						@for ($i = 1; $i < 4; $i++)
							@if ($i != $each->ma_trang_thai_dich_vu)
								<form action="{{ route('dich_vu.update', ['ma_dich_vu' => $each->ma_dich_vu]) }}" method="POST">
									{{ method_field('PUT') }}
									{{ csrf_field() }}
									<input type="hidden" name="ma_trang_thai_dich_vu" value="{{ $i }}">
									<input type="hidden" name="ten_dich_vu" value="{{ $each->ten_dich_vu }}">
									<input type="hidden" name="gia_dich_vu" value="{{ $each->gia_dich_vu }}">
									<input type="hidden" name="don_vi_dich_vu" value="{{ $each->don_vi_dich_vu }}">
									<button class="form_button_alternative">{{ $each->getTrangThaiDichVuForm($i) }}</button>
								</form>
							@endif
						@endfor
					</td>
					<td><a class="form_button_warning open_popup_form button_edit_dich_vu" data-url="{{ route('dich_vu.edit', ['ma_dich_vu' => $each->ma_dich_vu]) }}" data-url_action="{{ route('dich_vu.update', ['ma_dich_vu' => $each->ma_dich_vu]) }}">Sửa</a></td>
					<td>
						<button class="form_button_danger button_trigger">Xóa</button>
						<div style="display: none;">
							<form>
								{{ method_field('DELETE') }}
								{{ csrf_field() }}
								Bạn chắc chứ?
								<br>
								<button class="form_button_danger" formaction="{{ route('dich_vu.destroy', ['ma_dich_vu' => $each->ma_dich_vu]) }}" formmethod="POST">Xóa</button>
								<button class="form_button_return button_return">Quay lại</button>
							</form>
						</div>
					</td>
				</tr>
			@endforeach
			@endif
		</table>
		{{ $array_dich_vu->appends(['trang_thai_dich_vu' => $trang_thai_dich_vu, 'ten_dich_vu' => $ten_dich_vu])->render('layout.custom_paginate') }}
	</div>
</div>
@endsection

@push('script')
<script type="text/javascript">
	$(document).ready(function() {
		/* Active Select2 */
    	$('.search_item').select2({
    		width: 'resolve'
    	});
    	$('#trang_thai_dich_vu').select2({
    		placeholder: 'Chọn trạng thái'
    	});

    	/* Open form modal */
    	$('#button_create_dich_vu').click(function(event) {
			$('#create_dich_vu').show();
		});
		$('.button_edit_dich_vu').click(function(event) {
			var url = $(this).data('url');
			var url_action = $(this).data('url_action');
			$.ajax({
				url: url,
				type: 'GET',
				dataType: 'json',
			})
			.done(function(response) {
				$('#edit_dich_vu div form').attr('action', url_action);
				$('#ten_dich_vu_edit').val(response.dich_vu.ten_dich_vu);
				$('#gia_dich_vu_edit').val(response.dich_vu.gia_dich_vu);
				$('#don_vi_dich_vu_edit').val(response.dich_vu.don_vi_dich_vu);
				$('#edit_dich_vu').show();
			})
			.fail(function() {
				console.log("error");
			});
		});
	});
</script>
@endpush