routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('','LoginController@view_login')->name('view_login');
Route::post('process_login','LoginController@process_login')->name('process_login');

Route::group(['middleware' => 'CheckLogin'], function(){
	Route::get('welcome','LoginController@welcome')->name('welcome');
	Route::get('logout','LoginController@logout')->name('logout');
	Route::get('change_password','LoginController@change_password')->name('change_password');
	Route::post('update_admin_password','LoginController@update_admin_password')->name('update_admin_password');

	Route::resource('khach_hang','KhachHangController');
	Route::resource('hoa_don','HoaDonController');
	Route::resource('dich_vu','DichVuController');
	Route::resource('dat_dich_vu','DatDichVuController');
	Route::resource('dat_phong','DatPhongController');
	Route::resource('vat_tu','VatTuController');
	Route::resource('kho','KhoController');
	Route::resource('loai_phong','LoaiPhongController');
	Route::resource('loai_phong/{ma_loai_phong}/vat_tu','VatTuLoaiPhongController')->names('vat_tu_loai_phong');
	Route::resource('phong','PhongController');
	Route::resource('phong/{ma_phong}/vat_tu','VatTuPhongController')->names('vat_tu_phong');

	Route::get('thong_ke','ThongKeController@index')->name('thong_ke');
});

Route::group(['as' => 'ajax.', 'prefix' => 'ajax'], function() {
	Route::get('get_dich_vu','AjaxController@getDichVu')->name('get_dich_vu');
	Route::get('get_phong','AjaxController@getPhong')->name('get_phong');
	Route::get('get_hoa_don_phong','AjaxController@getHoaDonPhong')->name('get_hoa_don_phong');
	Route::get('get_thong_ke','AjaxController@getThongKe')->name('get_thong_ke');
	Route::get('get_thong_ke_noi_bat','AjaxController@getThongKeNoiBat')->name('get_thong_ke_noi_bat');
});

Route::resource('test_searching', 'TestController');

resources/views/layout/custom_paginate.blade.php
@if ($paginator->hasPages())
    <!-- Pagination -->
    <div class="pagination">
        {{-- Page Link List --}}
        <ul class="pagination">
            {{-- Previous Page Link --}}
            @if ($paginator->onFirstPage())
                <span>
                    <li class="disabled prev_next_pagination">
                        Trước
                    </li>
                </span>
            @else
                <a href="{{ $paginator->previousPageUrl() }}">
                    <li class="prev_next_pagination">
                        <span>Trước</span>
                    </li>
                </a>
            @endif

            {{-- Pagination Elements --}}
            @foreach ($elements as $element)
                {{-- Array Of Links --}}
                @if (is_array($element))
                    @foreach ($element as $page => $url)
                        @if ($page == $paginator->currentPage())
                            <span>
                                <li class="active">
                                    {{ $page }}
                                </li>
                            </span>
                        @elseif ($page == $paginator->currentPage() - 1 || $page == $paginator->currentPage() + 1 || $page == 1 || $page == $paginator->lastPage())
                            <a href="{{ $url }}">
                                <li>
                                    {{ $page }}
                                </li>
                            </a>
                        @elseif ($page == $paginator->lastPage() - 1 || $page == 2)
                            <span>
                                <li class="disabled">
                                    ...
                                </li>
                            </span>
                        @endif
                    @endforeach
                @endif
            @endforeach

            {{-- Next Page Link --}}
            @if ($paginator->hasMorePages())
                <li class="prev_next_pagination">
                    <span>
                        <a href="{{ $paginator->nextPageUrl() }}">
                            Sau
                        </a>
                    </span>
                </li>
            @else
                <span>
                    <li class="disabled prev_next_pagination">
                        Sau
                    </li>
                </span>
            @endif
        </ul>
        {{-- End Page Link List --}}

        {{-- Pagination Info Right --}}
        <div class="pagination_info_right">
            <p>
                {{ $paginator->lastItem() - $paginator->count() + 1 }} - {{ $paginator->lastItem() }} trên {{ $paginator->total() }} kết quả
            </p>
        </div>
        {{-- End Pagination Info Right --}}
    </div>
    <!-- Pagination -->
@endif

resources/views/layout/master.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>@yield('title') - Quản lý khách sạn</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="{{ asset('css/select2.min.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ asset('css/jquery-ui.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ asset('css/jquery.ui.datepicker.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ asset('css/fullcalendar/main.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ asset('css/custom_tooltip.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ asset('css/chart.min.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ asset('css/general.css') }}">
	@stack('css')
</head>
<body>
<div class="all">

	{{-- Sticky Shortcuts --}}
	<div>
		<button class="go_to_top" title="Lên đầu trang">↑</button>
		<button class="toggle_admin_modal" title="Cá nhân">
			<img src="{{ asset('Images/interface-BW/png/016-user.png') }}">
		</button>
	</div>

	{{-- Menu - Left tab --}}
	<div class="menu">
		<div class="div_title">
			<button class="navigation">←</button>
			<div class="title">
				<a href="{{ route('welcome') }}">Quản lý khách sạn</a>
			</div>
		</div>
		<div class="menu_h1 collapsible">
			<span class="menu_text_h1">
				Phòng
			</span>
		</div>
		<div class="menu_group_h2">
			<div class="menu_h2">
				<a href="{{ route('dat_phong.index') }}">
					<div class="menu_mini_h2">
						Đặt phòng
					</div>
				</a>
			</div>
			<div class="menu_h2">
				<a href="{{ route('loai_phong.index') }}">
					<div class="menu_mini_h2">
						Danh sách loại phòng
					</div>
				</a>
			</div>
			<div class="menu_h2">
				<a href="{{ route('phong.index') }}">
					<div class="menu_mini_h2">
						Danh sách phòng
					</div>
				</a>
			</div>
		</div>
		<div class="menu_h1 collapsible">
			<span class="menu_text_h1">
				Dịch vụ
			</span>
		</div>
		<div class="menu_group_h2">
			<div class="menu_h2">
				<a href="{{ route('dat_dich_vu.index') }}">
					<div class="menu_mini_h2">
						Đặt dịch vụ
					</div>
				</a>
			</div>
			<div class="menu_h2">
				<a href="{{ route('dich_vu.index') }}">
					<div class="menu_mini_h2">
						Danh sách dịch vụ
					</div>
				</a>
			</div>
		</div>
		<div class="menu_h1">
			<a href="{{ route('khach_hang.index') }}">
				<div class="menu_mini_h1">
					Khách hàng
				</div>
			</a>
		</div>
		<div class="menu_h1 collapsible">
			<span class="menu_text_h1">
				Vật tư
			</span>
		</div>
		<div class="menu_group_h2">
			<div class="menu_h2">
				<a href="{{ route('vat_tu.index') }}">
					<div class="menu_mini_h2">
						Danh sách vật tư
					</div>
				</a>
			</div>
			<div class="menu_h2">
				<a href="{{ route('kho.index') }}">
					<div class="menu_mini_h2">
						Kho
					</div>
				</a>
			</div>
		</div>
		<div class="menu_h1">
			<a href="{{ route('hoa_don.index') }}">
				<div class="menu_mini_h1">
					Hóa đơn
				</div>
			</a>
		</div>
		<div class="menu_h1">
			<a href="{{ route('thong_ke') }}">
				<div class="menu_mini_h1">
					Thống kê
				</div>
			</a>
		</div>
	</div>

	{{-- Overlay --}}
	<div class="overlay"></div>
	<div class="overlay_menu"></div>
	<div class="overlay_form"></div>

	{{-- Form Popup --}}
	<div class="form_popup_container">
		@yield('form_popup')
	</div>

	{{-- Admin Modal - Right tab --}}
	<div class="modal_admin">
		<div class="modal_admin_top">
			<div class="admin_avatar">
				<img src="{{ url('Images/interface-color/png/051-avatar.png') }}">
			</div>
			<div class="admin_info">
				<span>{{ Session::get('ho_ten') }}</span>
				<br>
				<span>{{ Session::get('email') }}</span>
			</div>
			<div class="admin_action">
				<div class="admin_action_button">
					<a href="{{ route('change_password') }}">
						Đổi mật khẩu
					</a>
				</div>
				<div class="admin_action_button">
					<a href="{{ route('logout') }}">
						Đăng xuất
					</a>
				</div>
			</div>
		</div>
	</div>

	{{-- Main content --}}
	<div class="content_big">
		<div class="header">
			{{-- Menu (Left Tab) button trigger (Mobile) --}}
			<div class="header_menu_toggle">
				<img src="{{ url('Images/interface-color/png/003-show.png') }}">
			</div>
			{{-- Username display, Admin tab (Right Tab) button trigger --}}
			<div class="header_username">
				<span>Chào {{ Session::get('ho_ten') }}</span>
			</div>
		</div>
		<div class="sub_header">
			{{-- Navigation pane --}}
			<div class="header_navigation">
				@yield('navigation')
			</div>
			{{-- Search pane --}}
			<div class="search">
				@yield('search')
			</div>
		</div>
		<div class="content">
			{{-- Success / Fail messages returned from Session --}}
			@if (Session::has('success'))
				<div class="success">
					<span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
					{{ Session::get('success') }}
				</div>
			@elseif (Session::has('alert'))
				<div class="alert">
					<span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
					{{ Session::get('alert') }}
				</div>
			@endif
			{{-- Success / Fail messages returned from Validation --}}
			@if ($errors->any())
			    <div class="alert">
			    	<span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
			    	Thao tác thất bại: {{ $errors->first() }}
			    </div>
			@endif
			{{-- Seprate noti div --}}
			<div id="noti"></div>
			@yield('content')
		</div>
	</div>
</div>
<script src="{{ asset('js/jquery.min.js') }}"></script>
<script src="{{ asset('js/jquery-ui.js') }}"></script>
<script src="{{ asset('js/select2.min.js') }}"></script>
<script src="{{ asset('js/fullcalendar/main.js') }}"></script>
<script src="{{ asset('js/fullcalendar/locales-all.js') }}"></script>
<script src="{{ asset('js/popper.min.js') }}"></script>
<script src="{{ asset('js/tooltip.min.js') }}"></script>
<script src="{{ asset('js/chart.min.js') }}"></script>
<script src="{{ asset('js/chart.bundle.min.js') }}"></script>
<script src="{{ asset('js/general.js') }}"></script>
@stack('script')
</body>
</html>