routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('','LoginController@view_login')->name('view_login');
Route::post('process_login','LoginController@process_login')->name('process_login');

Route::group(['middleware' => 'CheckLogin'], function(){
	Route::get('welcome','LoginController@welcome')->name('welcome');
	Route::get('logout','LoginController@logout')->name('logout');
	Route::get('change_password','LoginController@change_password')->name('change_password');
	Route::post('update_admin_password','LoginController@update_admin_password')->name('update_admin_password');

	Route::resource('khach_hang','KhachHangController');
	Route::resource('hoa_don','HoaDonController');
	Route::resource('dich_vu','DichVuController');
	Route::resource('dat_dich_vu','DatDichVuController');
	Route::resource('dat_phong','DatPhongController');
	Route::resource('vat_tu','VatTuController');
	Route::resource('kho','KhoController');
	Route::resource('loai_phong','LoaiPhongController');
	Route::resource('loai_phong/{ma_loai_phong}/vat_tu','VatTuLoaiPhongController')->names('vat_tu_loai_phong');
	Route::resource('phong','PhongController');
	Route::resource('phong/{ma_phong}/vat_tu','VatTuPhongController')->names('vat_tu_phong');

	Route::get('thong_ke','ThongKeController@index')->name('thong_ke');
});

Route::group(['as' => 'ajax.', 'prefix' => 'ajax'], function() {
	Route::get('get_dich_vu','AjaxController@getDichVu')->name('get_dich_vu');
	Route::get('get_phong','AjaxController@getPhong')->name('get_phong');
	Route::get('get_hoa_don_phong','AjaxController@getHoaDonPhong')->name('get_hoa_don_phong');
	Route::get('get_thong_ke','AjaxController@getThongKe')->name('get_thong_ke');
	Route::get('get_thong_ke_noi_bat','AjaxController@getThongKeNoiBat')->name('get_thong_ke_noi_bat');
});

Route::resource('test_searching', 'TestController');

app/Http/Controllers/KhachHangController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\KhachHangRequest;
use App\Models\KhachHangModel;

class KhachHangController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $array_khach_hang = KhachHangModel::all();

        return view('khach_hang.view_all_kh',[
            'array_khach_hang' => $array_khach_hang 
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('khach_hang.create_kh');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(KhachHangRequest $request)
    {
        try {
            $khach_hang               = new KhachHangModel();
            $khach_hang->ten_kh       = $request->get('ten_kh');
            $khach_hang->ngay_sinh_kh = $request->get('ngay_sinh_kh');
            $khach_hang->gioi_tinh_kh = $request->get('gioi_tinh_kh');
            $khach_hang->quoc_tich_kh = $request->get('quoc_tich_kh');
            $khach_hang->cmt_hc_kh    = $request->get('cmt_hc_kh');
            $khach_hang->email_kh     = $request->get('email_kh');
            $khach_hang->sdt_kh       = $request->get('sdt_kh');
            $khach_hang->save();

            return redirect()->route('khach_hang.index')->with('success','Thêm khách hàng thành công!');
        } catch (\Exception $e) {
            return redirect()->route('khach_hang.index')->with('alert','Có lỗi xảy ra, vui lòng thử lại');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($ma_kh)
    {
        $khach_hang = KhachHangModel::find($ma_kh);
        
        return json_encode(array('khach_hang' => $khach_hang));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(KhachHangRequest $request, $ma_kh)
    {
        try {
            KhachHangModel::find($ma_kh)->update($request->all());

            return redirect()->route('khach_hang.index')->with('success','Thay đổi thông tin khách hàng thành công!');
        } catch (\Exception $e) {
            return redirect()->route('khach_hang.index')->with('alert','Có lỗi xảy ra, vui lòng thử lại');
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($ma_kh)
    {
        //
    }
}

resources/views/khach_hang/create_kh.blade.php
@extends('layout.master')

@section('title', 'Thêm khách hàng')

@section('navigation')
<a href="{{ route('khach_hang.index') }}">Khách hàng</a> → Thêm khách hàng
@endsection

@section('search')
@endsection

@section('content')
<div class="grid_1">
	<div>
		Điền thông tin của khách hàng:
		<form id="formId" action="{{ route('khach_hang.store') }}" method="POST">
			{{ csrf_field() }}
			Họ và tên
			<br>
			<input type="text" name="ten_kh" value="{{ old('ten_kh') }}">
			@if ($errors->has('ten_kh'))
				<span class="validate_msg">{{ $errors->first('ten_kh') }}</span>
			@endif
			<br>
			Ngày sinh
			<br>
			<input type="date" name="ngay_sinh_kh" value="{{ old('ngay_sinh_kh') }}">
			@if ($errors->has('ngay_sinh_kh'))
				<span class="validate_msg">{{ $errors->first('ngay_sinh_kh') }}</span>
			@endif
			<br>
			Giới tính
			<br>
			<select name="gioi_tinh_kh" selected="">
				<option value="0" @if (old('gioi_tinh_kh') == 0) selected @endif>Nam</option>
				<option value="1" @if (old('gioi_tinh_kh') == 1) selected @endif>Nữ</option>
			</select>
			@if ($errors->has('gioi_tinh_kh'))
				<span class="validate_msg">{{ $errors->first('gioi_tinh_kh') }}</span>
			@endif
			<br>
			Quốc tịch
			<br>
			<input type="text" name="quoc_tich_kh" value="{{ old('quoc_tich_kh') }}">
			@if ($errors->has('quoc_tich_kh'))
				<span class="validate_msg">{{ $errors->first('quoc_tich_kh') }}</span>
			@endif
			<br>
			Chứng minh thư / Hộ chiếu
			<br>
			<input type="text" name="cmt_hc_kh" value="{{ old('cmt_hc_kh') }}">
			@if ($errors->has('cmt_hc_kh'))
				<span class="validate_msg">{{ $errors->first('cmt_hc_kh') }}</span>
			@endif
			<br>
			Email
			<br>
			<input type="text" name="email_kh" value="{{ old('email_kh') }}">
			@if ($errors->has('email_kh'))
				<span class="validate_msg">{{ $errors->first('email_kh') }}</span>
			@endif
			<br>
			Số điện thoại
			<br>
			<input type="text" name="sdt_kh" value="{{ old('sdt_kh') }}">
			@if ($errors->has('sdt_kh'))
				<span class="validate_msg">{{ $errors->first('sdt_kh') }}</span>
			@endif
			<br>
			<button id="button_submit" class="form_button_success">Thêm</button>
		</form>
	</div>
</div>
@endsection

{{-- @push('script')
<script type="text/javascript">
$(document).ready(function() {
	var url = '{{ route('khach_hang.store') }}';
	ajaxForm(url);
});
</script>
@endpush --}}

resources/views/khach_hang/edit_kh.blade.php
@extends('layout.master')

@section('title', 'Thay đổi thông tin khách hàng')

@section('navigation')
<a href="{{ route('khach_hang.index') }}">Khách hàng</a> → Thay đổi thông tin
@endsection

@section('search')
@endsection

@section('content')
<div class="grid_1">
	<div>
		Thay đổi thông tin của khách hàng:
		<form id="formId">
			{{ method_field('PUT') }}
			{{ csrf_field() }}
			Họ và tên
			<br>
			<input type="text" name="ten_kh" value="{{ $khach_hang->ten_kh }}">
			{{-- @if ($errors->has('ten_kh'))
				<span class="validate_msg">{{ $errors->first('ten_kh') }}</span>
			@endif --}}
			<br>
			Ngày sinh
			<br>
			<input type="date" name="ngay_sinh_kh" value="{{ $khach_hang->ngay_sinh_kh }}">
			{{-- @if ($errors->has('ngay_sinh_kh'))
				<span class="validate_msg">{{ $errors->first('ngay_sinh_kh') }}</span>
			@endif --}}
			<br>
			Giới tính
			<br>
			<select name="gioi_tinh_kh">
				@if ($khach_hang->gioi_tinh_kh == 0)
					<option value="0" selected>Nam</option>
					<option value="1">Nữ</option>
				@else
					<option value="0">Nam</option>
					<option value="1" selected>Nữ</option>
				@endif
			</select>
			{{-- @if ($errors->has('gioi_tinh_kh'))
				<span class="validate_msg">{{ $errors->first('gioi_tinh_kh') }}</span>
			@endif --}}
			<br>
			Quốc tịch
			<br>
			<input type="text" name="quoc_tich_kh" value="{{ $khach_hang->quoc_tich_kh }}">
			{{-- @if ($errors->has('quoc_tich_kh'))
				<span class="validate_msg">{{ $errors->first('quoc_tich_kh') }}</span>
			@endif --}}
			<br>
			Chứng minh thư / Hộ chiếu
			<br>
			<input type="text" name="cmt_hc_kh" value="{{ $khach_hang->cmt_hc_kh }}">
			{{-- @if ($errors->has('cmt_hc_kh'))
				<span class="validate_msg">{{ $errors->first('cmt_hc_kh') }}</span>
			@endif --}}
			<br>
			Email
			<br>
			<input type="text" name="email_kh" value="{{ $khach_hang->email_kh }}">
			{{-- @if ($errors->has('email_kh'))
				<span class="validate_msg">{{ $errors->first('email_kh') }}</span>
			@endif --}}
			<br>
			Số điện thoại
			<br>
			<input type="text" name="sdt_kh" value="{{ $khach_hang->sdt_kh }}">
			{{-- @if ($errors->has('sdt_kh'))
				<span class="validate_msg">{{ $errors->first('sdt_kh') }}</span>
			@endif --}}
			<br>
			<button id="button_submit" class="form_button_success">Chỉnh sửa</button>
		</form>
	</div>
</div>
@endsection

@push('script')
<script type="text/javascript">
$(document).ready(function() {
	var url = '{{ route('khach_hang.update',['ma' => $khach_hang->ma_kh]) }}';
	ajaxForm(url);
});
</script>
@endpush

resources/views/khach_hang/view_all_kh.blade.php
@extends('layout.master')

@section('title', 'Khách hàng')

@section('navigation')
Khách hàng
@endsection

@section('search')
@endsection

@section('form_popup')
<div class="form_popup" id="create_khach_hang">
	<div class="form_popup_header">
		<span class="form_popup_close_button">&times;</span>
		<span class="form_popup_title">Thêm khách hàng mới</span>
	</div>
	<div class="form_popup_content">
		<form action="{{ route('khach_hang.store') }}" method="POST">
		{{ csrf_field() }}
		<table class="form_popup_table">
			<tr>
				<td class="form_popup_td_label">Họ và tên</td>
				<td class="form_popup_td_input">
					<input type="text" name="ten_kh" placeholder="VD: Nguyễn Đình Ngân An" value="{{ old('ten_kh') }}">
				</td>
			</tr>
			<tr>
				<td class="form_popup_td_label">Ngày sinh</td>
				<td class="form_popup_td_input">
					<input type="date" name="ngay_sinh_kh" value="{{ old('ngay_sinh_kh') }}">
				</td>
			</tr>
			<tr>
				<td class="form_popup_td_label">Giới tính</td>
				<td class="form_popup_td_input">
					<select name="gioi_tinh_kh" id="gioi_tinh_kh">
						<option></option>
						<option value="0">Nam</option>
						<option value="1">Nữ</option>
					</select>
				</td>
			</tr>
			<tr>
				<td class="form_popup_td_label">Quốc tịch</td>
				<td class="form_popup_td_input">
					<input type="text" name="quoc_tich_kh" placeholder="VD: Việt Nam" value="{{ old('quoc_tich_kh') }}">
				</td>
			</tr>
			<tr>
				<td class="form_popup_td_label">Chứng minh thư / Hộ chiếu</td>
				<td class="form_popup_td_input">
					<input type="text" name="cmt_hc_kh" placeholder="VD: 001200000XXX" value="{{ old('cmt_hc_kh') }}">
				</td>
			</tr>
			<tr>
				<td class="form_popup_td_label">Email</td>
				<td class="form_popup_td_input">
					<input type="text" name="email_kh" placeholder="VD: test@demo.com" value="{{ old('email_kh') }}">
				</td>
			</tr>
			<tr>
				<td class="form_popup_td_label">Số điện thoại</td>
				<td class="form_popup_td_input">
					<input type="text" name="sdt_kh" placeholder="VD: 037337XXXX" value="{{ old('sdt_kh') }}">
				</td>
			</tr>
			<tr>
				<td colspan="2">
					<button class="form_button_success">Thêm</button>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>
<div class="form_popup" id="edit_khach_hang">
	<div class="form_popup_header">
		<span class="form_popup_close_button">&times;</span>
		<span class="form_popup_title">Thêm khách hàng mới</span>
	</div>
	<div class="form_popup_content">
		<form method="POST">
		{{ method_field('PUT') }}
		{{ csrf_field() }}
		<table class="form_popup_table">
			<tr>
				<td class="form_popup_td_label">Họ và tên</td>
				<td class="form_popup_td_input">
					<input type="text" name="ten_kh" placeholder="VD: Nguyễn Đình Ngân An" id="ten_kh_edit">
				</td>
			</tr>
			<tr>
				<td class="form_popup_td_label">Ngày sinh</td>
				<td class="form_popup_td_input">
					<input type="date" name="ngay_sinh_kh" id="ngay_sinh_kh_edit">
				</td>
			</tr>
			<tr>
				<td class="form_popup_td_label">Giới tính</td>
				<td class="form_popup_td_input">
					<select name="gioi_tinh_kh" id="gioi_tinh_kh_edit">
						<option value="0">Nam</option>
						<option value="1">Nữ</option>
					</select>
				</td>
			</tr>
			<tr>
				<td class="form_popup_td_label">Quốc tịch</td>
				<td class="form_popup_td_input">
					<input type="text" name="quoc_tich_kh" placeholder="VD: Việt Nam" id="quoc_tich_kh_edit">
				</td>
			</tr>
			<tr>
				<td class="form_popup_td_label">Chứng minh thư / Hộ chiếu</td>
				<td class="form_popup_td_input">
					<input type="text" name="cmt_hc_kh" placeholder="VD: 001200000XXX" id="cmt_hc_kh_edit">
				</td>
			</tr>
			<tr>
				<td class="form_popup_td_label">Email</td>
				<td class="form_popup_td_input">
					<input type="text" name="email_kh" placeholder="VD: test@demo.com" id="email_kh_edit">
				</td>
			</tr>
			<tr>
				<td class="form_popup_td_label">Số điện thoại</td>
				<td class="form_popup_td_input">
					<input type="text" name="sdt_kh" placeholder="VD: 037337XXXX" id="sdt_kh_edit">
				</td>
			</tr>
			<tr>
				<td colspan="2">
					<button class="form_button_success">Sửa</button>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>
@endsection

@section('content')
<div class="grid_1">
	<div class="grid_content">
		<a class="form_button_success open_popup_form" id="button_create_khach_hang">Thêm khách hàng</a>
		<table class="form_table">
			<tr>
				<th>Tên khách hàng</th>
				<th>Ngày sinh</th>
				<th>Giới tính</th>
				<th>Quốc tịch</th>
				<th>Chứng minh thư / hộ chiếu</th>
				<th>Email</th>
				<th>Số điện thoại</th>
				<th>Điều chỉnh</th>
			</tr>
			@foreach ($array_khach_hang as $each)
				<tr>
					<td>
						<p>
							{{ $each->ten_kh }}
						</p>
					</td>
					<td>
						<p>
							{{ $each->ngaySinhFormat() }}
						</p>
					</td>
					<td>
						<p>
							{{ $each->getGioiTinh() }}
						</p>
					</td>
					<td>
						<p>
							{{ $each->quoc_tich_kh }}
						</p>
					</td>
					<td>
						<p>
							{{ $each->cmt_hc_kh }}
						</p>
					</td>
					<td>
						<p>
							{{ $each->email_kh }}
						</p>
					</td>
					<td>
						<p>
							{{ $each->sdt_kh }}
						</p>
					</td>
					<td><a class="form_button_warning open_popup_form button_edit_khach_hang" data-url="{{ route('khach_hang.edit', ['ma' => $each->ma_kh]) }}" data-url_action="{{ route('khach_hang.update',['ma' => $each->ma_kh]) }}">Sửa</a></td>
					{{-- <td>
						<form action="{{ route('khach_hang.destroy',['ma' => $each->ma_kh]) }}" method="POST">
							{{ method_field('DELETE') }}
							{{ csrf_field() }}
							<button>Xóa</button>
						</form>
					</td> --}}
				</tr>
			@endforeach
		</table>
	</div>
</div>
@endsection

@push('script')
<script type="text/javascript">
	$(document).ready(function() {
		/* Active Select2 */
    	$('.search_item').select2({
    		width: 'resolve'
    	});
    	$('#gioi_tinh_kh').select2({
    		placeholder: 'Chọn giới tính'
    	});
    	$('#gioi_tinh_kh_edit').select2();

    	/* Open Form Modal */
    	$('#button_create_khach_hang').click(function(event) {
    		$('#create_khach_hang').show();
    	});
    	$('.button_edit_khach_hang').click(function(event) {
    		var url = $(this).data('url');
			var url_action = $(this).data('url_action');
			$.ajax({
				url: url,
				type: 'GET',
				dataType: 'json',
			})
			.done(function(response) {
				$('#edit_khach_hang div form').attr('action', url_action);
				$('#ten_kh_edit').val(response.khach_hang.ten_kh);
				$('#ngay_sinh_kh_edit').val(response.khach_hang.ngay_sinh_kh);
				$('#gioi_tinh_kh_edit option').each(function(index, el) {
					if ($(this).val() == response.khach_hang.gioi_tinh_kh) {
						$('#gioi_tinh_kh_edit').val($(this).val()).trigger('change');
					}
				});
				$('#quoc_tich_kh_edit').val(response.khach_hang.quoc_tich_kh);
				$('#cmt_hc_kh_edit').val(response.khach_hang.cmt_hc_kh);
				$('#email_kh_edit').val(response.khach_hang.email_kh);
				$('#sdt_kh_edit').val(response.khach_hang.sdt_kh);
				$('#edit_khach_hang').show();
			})
			.fail(function() {
				console.log("error");
			});
    	});
    });
</script>
@endpush