routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('','LoginController@view_login')->name('view_login');
Route::post('process_login','LoginController@process_login')->name('process_login');

Route::group(['middleware' => 'CheckLogin'], function(){
	Route::get('welcome','LoginController@welcome')->name('welcome');
	Route::get('logout','LoginController@logout')->name('logout');
	Route::get('change_password','LoginController@change_password')->name('change_password');
	Route::post('update_admin_password','LoginController@update_admin_password')->name('update_admin_password');

	Route::resource('khach_hang','KhachHangController');
	Route::resource('hoa_don','HoaDonController');
	Route::resource('dich_vu','DichVuController');
	Route::resource('dat_dich_vu','DatDichVuController');
	Route::resource('dat_phong','DatPhongController');
	Route::resource('vat_tu','VatTuController');
	Route::resource('kho','KhoController');
	Route::resource('loai_phong','LoaiPhongController');
	Route::resource('loai_phong/{ma_loai_phong}/vat_tu','VatTuLoaiPhongController')->names('vat_tu_loai_phong');
	Route::resource('phong','PhongController');
	Route::resource('phong/{ma_phong}/vat_tu','VatTuPhongController')->names('vat_tu_phong');

	Route::get('thong_ke','ThongKeController@index')->name('thong_ke');
});

Route::group(['as' => 'ajax.', 'prefix' => 'ajax'], function() {
	Route::get('get_dich_vu','AjaxController@getDichVu')->name('get_dich_vu');
	Route::get('get_phong','AjaxController@getPhong')->name('get_phong');
	Route::get('get_hoa_don_phong','AjaxController@getHoaDonPhong')->name('get_hoa_don_phong');
	Route::get('get_thong_ke','AjaxController@getThongKe')->name('get_thong_ke');
	Route::get('get_thong_ke_noi_bat','AjaxController@getThongKeNoiBat')->name('get_thong_ke_noi_bat');
});

Route::resource('test_searching', 'TestController');

app/Http/Controllers/HoaDonController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\HoaDonRequest;
use App\Models\KhachHangModel;
use App\Models\HoaDonModel;
use App\Models\HoaDonDichVuModel;
use App\Models\SuDungDichVuModel;
use App\Models\HoaDonPhongModel;
use DB;

class HoaDonController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $array_hoa_don = HoaDonModel::join('khach_hang','hoa_don.ma_kh','=','khach_hang.ma_kh')
            ->join('trang_thai_hoa_don','hoa_don.ma_trang_thai_hoa_don','trang_thai_hoa_don.ma_trang_thai_hoa_don')
            ->with([
                'array_hoa_don_dich_vu' => function($query){
                    $query
                    ->select(DB::raw('sum(gia_sd_dich_vu * so_luong_dich_vu) as tong_tien_dich_vu'), 'ma_hoa_don')
                    ->groupBy('ma_hoa_don');
                },
                'array_hoa_don_phong' => function($query){
                    $query
                    ->select(DB::raw('round(gia_dat_phong/3 * ceil(sum(time_to_sec(timediff(hoa_don_phong.thoi_gian_di,hoa_don_phong.thoi_gian_den)))/28800),-2) as tong_tien_phong'), 'ma_hoa_don')
                    ->groupBy('ma_hoa_don','ma_phong');
                }
            ])
            ->select('hoa_don.*','khach_hang.ten_kh as ten_kh','trang_thai_hoa_don.*')
            ->get();
            
        $array_khach_hang = KhachHangModel::leftJoin('hoa_don','khach_hang.ma_kh','=','hoa_don.ma_kh')
            ->select('khach_hang.*')
            ->whereNull('ma_trang_thai_hoa_don')
            ->orWhere('ma_trang_thai_hoa_don','!=',1)
            ->distinct()
            ->get();

        return view('hoa_don.view_all_hd',[
            'array_hoa_don'    => $array_hoa_don,
            'array_khach_hang' => $array_khach_hang
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(HoaDonRequest $request)
    {
        try {
            $currentTime = date('Y-m-d H:i:s');
            $ghi_chu = ($request->ghi_chu == null) ? '' : $request->ghi_chu ;

            $hoa_don                        = new HoaDonModel();
            $hoa_don->ma_kh                 = $request->ma_kh;
            $hoa_don->thoi_gian_lap_hoa_don = $currentTime;
            $hoa_don->ma_trang_thai_hoa_don = 1;
            $hoa_don->ghi_chu               = $ghi_chu;
            $hoa_don->save();

            return redirect()->route('hoa_don.index')->with('success','Thêm hóa đơn thành công!');
        } catch (\Exception $e) {
            return redirect()->route('hoa_don.index')->with('alert','Có lỗi xảy ra, vui lòng thử lại');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($ma_hoa_don)
    {
        $array_hoa_don = HoaDonModel::where('ma_hoa_don','=',$ma_hoa_don)
            ->join('khach_hang','hoa_don.ma_kh','khach_hang.ma_kh')
            ->join('trang_thai_hoa_don','hoa_don.ma_trang_thai_hoa_don','trang_thai_hoa_don.ma_trang_thai_hoa_don')
            ->with([
                'array_hoa_don_dich_vu' => function($query){
                    $query
                    ->select(DB::raw('SUM(gia_sd_dich_vu * so_luong_dich_vu) as tong_tien_dich_vu'), 'ma_hoa_don')
                    ->groupBy('ma_hoa_don');
                },
                'array_hoa_don_phong' => function($query){
                    $query
                    ->select(DB::raw('round(gia_dat_phong/3 * ceil(sum(time_to_sec(timediff(thoi_gian_di,thoi_gian_den)))/28800),-2) as tong_tien_phong'), 'ma_hoa_don')
                    ->groupBy('ma_hoa_don','ma_phong');
                }
            ])
            ->select('hoa_don.*','khach_hang.ten_kh as ten_kh','trang_thai_hoa_don.*')
            ->get();

        $array_hoa_don_phong = HoaDonPhongModel::join('phong','hoa_don_phong.ma_phong','phong.ma_phong')
            ->where('ma_hoa_don','=',$ma_hoa_don)
            ->orderBy('ma_hoa_don')
            ->get();

        $array_hoa_don_dich_vu = HoaDonDichVuModel::join('dich_vu','hoa_don_dich_vu.ma_dich_vu','dich_vu.ma_dich_vu')
            ->where('ma_hoa_don','=',$ma_hoa_don)
            ->orderBy('thoi_gian_sd_dich_vu')
            ->get();

        $array_hoa_don_phong_group_by = HoaDonPhongModel::join('phong','hoa_don_phong.ma_phong','phong.ma_phong')
            ->where('ma_hoa_don','=',$ma_hoa_don)
            ->select('phong.ten_phong','hoa_don_phong.gia_dat_phong')
            ->selectRaw('sum(time_to_sec(timediff(hoa_don_phong.thoi_gian_di,hoa_don_phong.thoi_gian_den))) as tong_thoi_gian_thue_phong')
            ->selectRaw('ceil(sum(time_to_sec(timediff(hoa_don_phong.thoi_gian_di,hoa_don_phong.thoi_gian_den)))/28800) as he_so_thoi_gian_thue')
            ->groupBy('phong.ma_phong','hoa_don_phong.gia_dat_phong')
            ->get();

        $array_hoa_don_dich_vu_group_by = HoaDonDichVuModel::join('dich_vu','hoa_don_dich_vu.ma_dich_vu','dich_vu.ma_dich_vu')
            ->where('ma_hoa_don','=',$ma_hoa_don)
            ->select('dich_vu.ten_dich_vu','hoa_don_dich_vu.gia_sd_dich_vu','dich_vu.don_vi_dich_vu')
            ->selectRaw('sum(hoa_don_dich_vu.so_luong_dich_vu) as so_luong_dich_vu')
            ->selectRaw('sum(gia_sd_dich_vu * so_luong_dich_vu) as tong_tien_dich_vu')
            ->groupBy('dich_vu.ma_dich_vu','hoa_don_dich_vu.gia_sd_dich_vu')
            ->get();

        // return $array_hoa_don;

        return view('hoa_don.view_details_hd', [
            'array_hoa_don'                  => $array_hoa_don,
            'array_hoa_don_phong'            => $array_hoa_don_phong,
            'array_hoa_don_dich_vu'          => $array_hoa_don_dich_vu,
            'array_hoa_don_phong_group_by'   => $array_hoa_don_phong_group_by,
            'array_hoa_don_dich_vu_group_by' => $array_hoa_don_dich_vu_group_by
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($ma_hoa_don)
    {
        $hoa_don = HoaDonModel::join('khach_hang','hoa_don.ma_kh','khach_hang.ma_kh')
            ->where('ma_hoa_don',$ma_hoa_don)
            ->first();

        return json_encode(array('hoa_don' => $hoa_don));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $ma_hoa_don)
    {
        try {
            HoaDonModel::where('ma_hoa_don',$ma_hoa_don)->update($request->only((new HoaDonModel)->getFillable()));

            if ($request->has('ma_trang_thai_hoa_don') == true) {
                return redirect()->route('hoa_don.index')->with('success','Thay đổi trạng thái hóa đơn thành công!');
            }
            return redirect()->route('hoa_don.index')->with('success','Sửa đổi ghi chú hóa đơn thành công!');
        } catch (\Exception $e) {
            return redirect()->route('hoa_don.index')->with('alert','Có lỗi xảy ra, vui lòng thử lại');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/hoa_don/create_hd.blade.php
@extends('layout.master')

@section('title', 'Hóa đơn')

@section('navigation')
<a href="{{ route('hoa_don.index') }}">Hóa đơn</a> → Tạo hóa đơn
@endsection

@section('search')
@endsection

@section('content')
<div class="grid_1">
	<div>
		<form action="{{ route('hoa_don.store') }}" method="POST">
			{{ csrf_field() }}
			Tạo hóa đơn mới:
			<br>
			Khách hàng
			<br>
			<select name="ma_kh">
				<option disabled selected>Khách hàng</option>
				@foreach ($array_khach_hang as $each)
					<option value="{{ $each->ma_kh }}">{{ $each->ten_kh }}</option>
				@endforeach
			</select>
			@if ($errors->has('ma_kh'))
				<span class="validate_msg">{{ $errors->first('ma_kh') }}</span>
			@endif
			<br>
			Ghi chú
			<br>
			<textarea name="ghi_chu"></textarea>
			<br>
			<button class="form_button_success">Thêm</button>
			*Lưu ý: Thời gian tạo hóa đơn sẽ lấy thời gian hiện tại
		</form>
	</div>
</div>
@endsection

resources/views/hoa_don/ghi_chu_hd.blade.php
@extends('layout.master')

@section('title', 'Hóa đơn')

@section('navigation')
<a href="{{ route('hoa_don.index') }}">Hóa đơn</a> → Chỉnh sửa ghi chú
@endsection

@section('search')
@endsection

@section('content')
<div class="grid_1">
	<div>
		<form action="{{ route('hoa_don.update', ['ma_hoa_don' => $hoa_don->ma_hoa_don]) }}" method="POST">
			{{ method_field('PUT') }}
			{{ csrf_field() }}
			Hóa đơn: <input type="text" disabled value="{{ $hoa_don->ten_kh }} #{{ $hoa_don->ma_hoa_don }}">
			<br>
			Ghi chú
			<br>
			<textarea name="ghi_chu">{{ $hoa_don->ghi_chu }}</textarea>
			<br>
			<button class="form_button_success">Thay đổi</button>
		</form>
	</div>
</div>
@endsection

resources/views/hoa_don/view_all_hd.blade.php
@extends('layout.master')

@section('title', 'Hóa đơn')

@section('navigation')
Hóa đơn
@endsection

@section('search')
@endsection

@section('form_popup')
<div class="form_popup" id="create_hoa_don">
	<div class="form_popup_header">
		<span class="form_popup_close_button">&times;</span>
		<span class="form_popup_title">Thêm hóa đơn mới</span>
	</div>
	<div class="form_popup_content">
		<form action="{{ route('hoa_don.store') }}" method="POST">
		{{ csrf_field() }}
		<table class="form_popup_table">
			<tr>
				<td class="form_popup_td_label">Khách hàng</td>
				<td class="form_popup_td_input">
					<select name="ma_kh" id="ma_kh">
						<option></option>
						@foreach ($array_khach_hang as $each)
							<option value="{{ $each->ma_kh }}">{{ $each->ten_kh }}</option>
						@endforeach
					</select>
				</td>
			</tr>
			<tr>
				<td class="form_popup_td_label">Ghi chú</td>
				<td class="form_popup_td_input">
					<textarea name="ghi_chu" value="{{ old('ghi_chu') }}"></textarea>
				</td>
			</tr>
			<tr>
				<td colspan="2">
					<button class="form_button_success">Thêm</button>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>
<div class="form_popup" id="edit_hoa_don">
	<div class="form_popup_header">
		<span class="form_popup_close_button">&times;</span>
		<span class="form_popup_title">Chỉnh sửa ghi chú</span>
	</div>
	<div class="form_popup_content">
		<form method="POST">
		{{ method_field('PUT') }}
		{{ csrf_field() }}
		<table class="form_popup_table">
			<tr>
				<td class="form_popup_td_label">Khách hàng</td>
				<td class="form_popup_td_input">
					<input type="hidden" name="ma_kh" id="ma_kh_edit">
					<span id="ten_kh_edit"></span>
				</td>
			</tr>
			<tr>
				<td class="form_popup_td_label">Ghi chú</td>
				<td class="form_popup_td_input">
					<textarea name="ghi_chu" id="ghi_chu_edit"></textarea>
				</td>
			</tr>
			<tr>
				<td colspan="2">
					<button class="form_button_success">Sửa</button>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>
@endsection

@section('content')
<div class="grid_1">
	<div class="grid_content">
		<a class="form_button_success open_popup_form" id="button_create_hoa_don">Tạo hóa đơn mới</a>
		<table class="form_table">
			<tr>
				<th>Hóa đơn</th>
				<th>Thời gian lập hóa đơn</th>
				<th>Trạng thái hóa đơn</th>
				<th>Ghi chú</th>
				<th>Thành tiền (VND)</th>
				<th>Xem chi tiết</th>
				<th colspan="2">Thao tác</th>
			</tr>
			@foreach ($array_hoa_don as $each)
				<tr>
					<td>
						<p>
							{{ $each->ten_kh }} - #{{ $each->ma_hoa_don }}
						</p>
					</td>
					<td>
						<p>
							{{ $each->getThoiGianLapHoaDon() }}
						</p>
					</td>
					<td>
						<p>
							{{ $each->ten_trang_thai_hoa_don }}
						</p>
					</td>
					<td>
						<p>
							{{ $each->ghi_chu }}
						</p>
					</td>
					<td>
						<p>
							@php
								$tong_tien_phong = 0
							@endphp
							@if (count($each->array_hoa_don_dich_vu))
								@if (count($each->array_hoa_don_phong))
									@foreach ($each->array_hoa_don_dich_vu as $hoa_don_dich_vu)
										@foreach ($each->array_hoa_don_phong as $hoa_don_phong)
											@php
												$tong_tien_phong += $hoa_don_phong->tong_tien_phong;
											@endphp
										@endforeach
									@endforeach
									{{ number_format($hoa_don_dich_vu->tong_tien_dich_vu + $tong_tien_phong) }}
								@else
									@foreach ($each->array_hoa_don_dich_vu as $hoa_don_dich_vu)
										{{ number_format($hoa_don_dich_vu->tong_tien_dich_vu) }}
									@endforeach
								@endif
							@else
								@if (count($each->array_hoa_don_phong))
									@foreach ($each->array_hoa_don_phong as $hoa_don_phong)
										@php
											$tong_tien_phong += $hoa_don_phong->tong_tien_phong;
										@endphp
									@endforeach
									{{ number_format($hoa_don_phong->tong_tien_phong) }}
								@else
									0
								@endif
							@endif
							đ
						</p>
					</td>
					<td><a href="{{ route('hoa_don.show', ['ma_hoa_don' => $each->ma_hoa_don]) }}" class="form_button_redirect">Xem</a></td>
					<td><a class="form_button_warning open_popup_form button_edit_hoa_don" data-url="{{ route('hoa_don.edit', ['ma_hoa_don' => $each->ma_hoa_don]) }}" data-url_action="{{ route('hoa_don.update', ['ma_hoa_don' => $each->ma_hoa_don]) }}">Sửa ghi chú</a></td>
					<td>
						@if ($each->ma_trang_thai_hoa_don == 2)
							<button disabled class="form_button_alternative button_disabled">Đã thanh toán</button>
						@elseif ($each->ma_trang_thai_hoa_don == 3)
							<button disabled class="form_button_danger button_disabled">Đã hủy</button>
						@else
							@for ($i = 1; $i < 4; $i++)
								@if ($i != $each->ma_trang_thai_hoa_don)
									<form action="{{ route('hoa_don.update', ['ma_hoa_don' => $each->ma_hoa_don]) }}" method="POST">
										{{ method_field('PUT') }}
										{{ csrf_field() }}
										<input type="hidden" name="ma_trang_thai_hoa_don" value="{{ $i }}">
										@if ($i == 2)
											<button class="form_button_alternative">Thanh toán</button>
										@else
											<button class="form_button_danger">Hủy</button>
										@endif
									</form>
								@endif
							@endfor
						@endif
					</td>
				</tr>
			@endforeach
		</table>
	</div>
</div>
@endsection

@push('script')
<script type="text/javascript">
	$(document).ready(function() {
		/* Active Select2 */
    	$('.search_item').select2({
    		width: 'resolve'
    	});
    	$('#ma_kh').select2({
    		placeholder: 'Chọn khách hàng'
    	});

    	/* Open Form Modal */
    	$('#button_create_hoa_don').click(function(event) {
    		$('#create_hoa_don').show();
    	});
    	$('.button_edit_hoa_don').click(function(event) {
    		var url = $(this).data('url');
			var url_action = $(this).data('url_action');
			$.ajax({
				url: url,
				type: 'GET',
				dataType: 'json',
			})
			.done(function(response) {
				$('#edit_hoa_don div form').attr('action', url_action);
				$('#ma_kh_edit').val(response.hoa_don.ma_kh);
				$('#ten_kh_edit').html(response.hoa_don.ten_kh);
				$('#ghi_chu_edit').val(response.hoa_don.ghi_chu);
				$('#edit_hoa_don').show();
			})
			.fail(function() {
				console.log("error");
			});
    	});
    });
</script>
@endpush